name: Run Unit Tests

on:  
  push:  
    branches: [main, dev]  # Lance les tests à chaque push sur main et dev
  pull_request:  
    branches: [main]  # Vérifie aussi lors des pull requests sur main

jobs:  
  test:  
    runs-on: ubuntu-latest  # Exécute les tests sur Ubuntu

    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v3  # Récupère le code du repo

      - name: Set up Python  
        uses: actions/setup-python@v4  
        with:  
          python-version: "3.9"  # Installe Python 3.9

      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          pip install -r requirements.txt  # Installe les dépendances

      - name: Run tests  
        run: |  
          pytest test_matching_cv.py  # Lance les tests unitaires
